# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Miles Martinez
tagline:          'Who even am I!'
description:      'Currently a graduate student @<a href="http://scholars.duke.edu" target="_blank">Duke University</a> studying ~cognitive neuroscience~ <br> This is also me but dumb <a href="https://twitter.com/Mr__Kilometers" target="_blank">@Mr__Kilometers</a>.'
url:              http://mdmarti.github.io
baseurl:          /

author:
  name:           'Miles Martinez'
  url:            https://twitter.com/Mr__Kilometers

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdmarti/mdmarti.github.io