# Site settings
title: Miles Martinez
email: miles.martinez@duke.edu
url: https://github.com/jeromelachaud/freelancer-theme
description: "A website for Miles Martinez's accomplishments."
keywords: "neuroscience, computational, deep learning, representation learning, motor learning, systems neuroscience, computational neuroscience"
skills: "PhD Candidate in ECE, Computational Neuroscientist"
meta_author: Martinez Miles

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag) 
color:
  primary: 00592e #80B3FF #Dusky green
  primary-rgb: "0,89,46" #"128,179,255"
  background-2: 00592e #80B3FF #Dusky green 2ee670 # royal blue # sea green
  secondary:  003e8a # Vandar Poel's blue eugenia red #ffffff
  secondary-dark:  2ee670 # royal blue # sea green ff331a # peach red #ffe600 #FD6E8A #apricot yellow
  tertiary: 

# Footer settings
footer:
  copyright: Miles Martinez
  location: Location
  social: On Line
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url: 
  - title: github
    url: http://github.com/mdmarti

# Postal address (add as many lines as necessary)
address:
  - line: Wouldn't you
  - line: like to know

# Credits content
credits: 'Website built using Freelancer: a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for  posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""


